version: '3'
services:
  devbox:
    build:
      context: ./
      dockerfile: DevBox.DockerFile
    container_name: DevApache
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../www:/var/www/html
    networks:
      - dev-network
      
  devmysql:
    image: mysql:5.7
    container_name: DevMysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'abcd1234'
      SERVICE_TAGS: dev
      SERVICE_NAME: dev-mysql
    restart: unless-stopped
    volumes:
      - ./dbdata:/var/lib/mysql/
    networks:
      - dev-network
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    links: 
      - devmysql:dev-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
      PMA_HOST: dev-mysql  
    networks:
      - dev-network
  
networks:
  dev-network:
    driver: bridge